### ISSUE TITLE
PublishPlugin Task Failed

### ISSUE THREAD

**Issue by Drjacky** [JetBrains/intellij-platform-gradle-plugin#1533] opened 2024-01-30 13:17 UTC
### What happened?

Github Action -> publishPlugin task fails:

https://github.com/Drjacky/Avocado/actions/runs/7709858760/job/21011916928
latest try: https://github.com/Drjacky/Avocado/actions/runs/7709858760/job/21017535162

All the secrets(including PUBLISH_TOKEN) are provided!
![image](https://github.com/JetBrains/gradle-intellij-plugin/assets/2296754/fa30264d-3355-49ed-a9c7-a21e7909d59b)

Related thread: https://github.com/JetBrains/gradle-intellij-plugin/issues/1513

### Relevant log output or stack trace

```shell
> Task :jarSearchableOptions FROM-CACHE

> Task :buildPlugin
FAILURE: Build failed with an exception.

> Task :signPlugin SKIPPED
* What went wrong:
> Task :publishPlugin FAILED
Execution failed for task ':publishPlugin'.
18 actionable tasks: 14 executed, 4 from cache
> token property must be specified for plugin publishing
Configuration cache entry stored.
```

### Steps to reproduce

Tru to publish the plugin through Github Actions

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

8.5

### Operating System

None

### Link to build, i.e. failing GitHub Action job

https://github.com/Drjacky/Avocado/actions/runs/7709858760/job/21017535162

**Comment by hsz** [comment] 2024-07-14 07:12
Duplicate of #1540

**Closed by hsz** 2024-07-14 07:12 UTC
Labels: bug
