### ISSUE TITLE
In tests, class `GoFileType` is unavailable at runtime with 2024.3eap

### ISSUE THREAD

**Issue by jansorg** [JetBrains/intellij-platform-gradle-plugin#1798] opened 2024-10-15 09:23 UTC
### What happened?

This test compiles, but does not run:
https://github.com/jansorg/2024.3-godep-demo/blob/main/src/test/kotlin/dev/ja/godepdemo/godepdemo/GoFileTypeActionTest.kt

`GoFileType` is available at compile time, but is not available at runtime.

With 2024.2, the test is passing.
It's not passing with 2024.3 eap.
Adding a dependency on `intellij.go.frontback` does not work, because the module doesn't exist (apparently, although there's a `intellij.go.frontback.xml`).

With 2.1.0 and 2024.3 eap it's currently not possible to develop Go-aware code.

### Steps to reproduce

1. Clone https://github.com/jansorg/2024.3-godep-demo.git
2. Run tests

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.10.2

### Operating System

Linux

**Comment by jansorg** [comment] 2024-10-15 09:30
It's also broken for `PhpFileType`

**Comment by AlexanderBartash** [comment] 2024-10-15 12:09
Add at least one bundled plugin dependency, I think just anyone might work, without it things do not work as expected.

**Comment by AlexanderBartash** [comment] 2024-10-15 12:54
I think the issue is that when you  have no bundled plugins & modules and add just a 3rd party plugin, when you start an IDE everything seems to work because the Gradle plugin does not attempt to disable non-included bundled plugins, because they are bundled. But, when you run tests somehow it does that. You can see that in the log file I mentioned.

On the left is just Go in tests (not loaded), on the right is go +
```
bundledPlugin("com.intellij.platform.images")
bundledPlugin("com.intellij.copyright")
bundledPlugin("com.intellij.java")
```
On the bottom is runIde task logs
![image](https://github.com/user-attachments/assets/9516f631-bf86-4e24-b105-1e33cff22e36)

Probably the proper workaround for now is look for a log like:
```
2024-10-15 15:11:41,840 [    316]   INFO - #c.i.i.p.PluginManager - Module intellij.platform.images.backend.svg is not enabled because dependency com.intellij.platform.images is not available
Module intellij.platform.images.copyright is not enabled because dependency com.intellij.platform.images is not available
Module intellij.kotlin.onboarding-promoter is not enabled because dependency kotlin.features-trainer is not available
Module intellij.profiler.ultimate is not enabled because dependency com.intellij.java is not available
```
And add what it wants.

This reminds me of https://youtrack.jetbrains.com/issue/IDEA-337162

**Comment by AlexanderBartash** [comment] 2024-10-15 15:28
It may be actually caused just by `com.intellij.modules.json` dependency. Go added that in 243:
![image](https://github.com/user-attachments/assets/41431a95-bd50-4cbe-8d1d-360605181312)
Also adding just `bundledPlugin("com.intellij.modules.json")` fixed the build.

Also this code might be playing a role here:
https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/5fd4e690bab462522f988dbe2ccb451228eb69f5/src/main/kotlin/org/jetbrains/intellij/platform/gradle/providers/ModuleDescriptorsValueSource.kt#L62

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/a4e556c9e1162466f8c0fa7d042462661b835f49/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformDependenciesHelper.kt#L1180

**Comment by jansorg** [comment] 2024-10-15 16:29
Oh, my. Thank you, that would explain it!
I really wish transitive (and available) dependencies would be added automatically...

**Comment by AlexanderBartash** [comment] 2024-10-15 19:50
Yeah, adding them is a bit tricky. A bit more on what is going on.

In 243 Go plugin has only these dependencies (if its modules are not taken into account):
```xml
<plugin id="com.intellij.modules.lang"/>
<plugin id="com.intellij.modules.ultimate"/>
<plugin id="com.intellij.modules.go-capable"/>
<module name="intellij.platform.vcs.impl"/>
```
JSON here probably was part of the default IDE capabilities, i.e. always available on the classpath.  So it was not defined as a dependency.

Then JSON was moved into a bundled plugin. Which may seem irrelevant, since it is bundled, so why should it matter. So in 243 JSON was added to Go plugin dependencies:
```xml
<plugin id="com.intellij.modules.lang"/>
<plugin id="com.intellij.modules.ultimate"/>
<plugin id="com.intellij.modules.go-capable"/>
<plugin id="com.intellij.modules.json"/>
<module name="intellij.platform.vcs.impl"/>
```
It is important to note, that all these dependencies in the list (except JSON in 243) also look like a part of the default IDE capabilities, i.e. always available on the classpath.

It seems that when the test task runs, it behaves differently from the runIde task:
 - runIde by default loads all bundled plugins
 - test task starts the IDE in a headless mode with all plugins disabled, including bundled plugins.


Which means that in 243 the test task does not load JSON by default, unless a dependency is declared on it. Go probably was not loaded simply because it has a non-optional dependency on JSON.

The reason why `bundledPlugin("com.intellij.modules.json")` because it adds JSON plugin to test's classpath, so that it can be loaded in runtime.



As far as I know, this plugin does look at dependencies of the 3rd party plugins and does not add them automatically to the classpath.

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/bf8fc7fa180ef9c797d18e3b66b3f743532449a3/src/main/kotlin/org/jetbrains/intellij/platform/gradle/shim/PluginArtifactoryShim.kt#L71



Again, it does not  matter (not visible) during runIde because it loads everything. But it matters in tests.

To fix this, either:
- Everyone should declare dependencies on all transitive dependencies of all 3rd party plugins added as a dependency.
- This plugin should add those dependencies automatically once plugin zip is downloaded, which is a bit tricky because it is a zip, and it is unzipped not using a transform. So after it is unzipped we have to look inside and parse its plugin.xml



Currently the code above does not declare any dependencies for the created IvyModule.

**Comment by Undin** [comment] 2024-10-16 12:43
Actually, it's almost the same as #1791. The only difference is that here the plugin which is not loaded automatically is `com.intellij.modules.json` instead of `intellij.charts`

And from my POV such required dependencies should be loaded automatically (at least if we are talking about bundled plugins) like common transitive dependencies of your external plugins

@hsz WDYT?

**Comment by AlexanderBartash** [comment] 2024-10-16 12:46
@Undin For bundled plugins, dependencies are added:

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/33af9bdd1d0d8b996b911781ab23013dd14997f4/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformDependenciesHelper.kt#L773

Even transitive (notice the recursion):
https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/33af9bdd1d0d8b996b911781ab23013dd14997f4/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformDependenciesHelper.kt#L839

**Comment by AlexanderBartash** [comment] 2024-10-16 13:55
@Undin Yes, maybe. Try to open Gradle tool window and go to dependencies. You will notice that bundled plugins could have many transitive dependencies.

![image](https://github.com/user-attachments/assets/beb28d50-cc5f-4ab9-ad93-949fa0254501)
(I do not guarantee that it will look the same for you, because I am using my own build of the plugin with not yet released changes.)

**Comment by Undin** [comment] 2024-10-16 13:55
Anyway, it's quite unexpected that converting bundled IDE module into bundled plugin (i.e. pure internal thing) may break tests. And it may take quite a lot of time to understand the reason if you haven't faced with similar things before

**Comment by Undin** [comment] 2024-10-16 14:02
@AlexanderBartash Sorry, but I don't understand what you want to say. I understand that bundled plugins have dependencies, that it's possible to find them either with Gradle tool window or inside ivy xml files located in `intellijPlatform/localPlatformArtifacts` dir.
But all these facts don't help, unfortunately. At least, from the users' point of view. And I don't think that it's ok to force users to dive into dependencies of bundled plugins and how intellij platform gradle plugin works. It should just work. Currently, it doesn't work in this way ⇒ it should be fixed

**Comment by AlexanderBartash** [comment] 2024-10-16 14:03
@Undin I just updated my https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1798#issuecomment-2416922554 above, with a more proper example. In the database plugin you can see transitive deps, why `grid.impl` does not have any deps there is a mystery to me.

**Comment by AlexanderBartash** [comment] 2024-10-16 14:04
> @AlexanderBartash Sorry, but I don't understand what you want to say. I understand that bundled plugins have dependencies, that it's possible to find them either with Gradle tool window or inside ivy xml files located in `.intellijPlatform/localPlatformArtifacts` dir. But all these facts don't help, unfortunately. At least, from the users' point of view. And I don't think that it's ok to force users to dive into dependencies of bundled plugins and how intellij platform gradle plugin works. It should just work. Currently, it doesn't work in this way ⇒ it should be fixed

Those dependencies in Gradle tool window or in Ivy files are exactly the transitive dependencies created by this plugin. Links to the code provided in https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1798#issuecomment-2416746369

Those dependencies should be available on the classpath.

**Comment by AlexanderBartash** [comment] 2024-10-16 14:10
@Undin Just for clarification, because it was confusing me too. Those ivy files do not mean that plugins are downloaded from a real ivy repo. Those files are created by this plugin in a dir, then the dir is simply registered in Gradle as a local Ivy repo, so that Gradle can understand where to find the jars by looking at Ivy files.

If we assume that this plugin has a bug leading to a missing transitive dependency, it will be missing in the Ivy files too, because the plugin creates them. Also it will be missing in that Gradle tool window, because that is probably the same as `./gradlew dependencies`

That is simply the way this plugin adds dependencies to Gradle today.

**Comment by AlexanderBartash** [comment] 2024-10-16 16:31
@Undin There is a bug with recursion in https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/33af9bdd1d0d8b996b911781ab23013dd14997f4/src/main/kotlin/org/jetbrains/intellij/platform/gradle/extensions/IntelliJPlatformDependenciesHelper.kt#L839

That is the reason for #1791

**Comment by hsz** [comment] 2024-12-04 08:57
@jansorg Thanks for reporting.
With the recent changes, your demo project works correctly, and all tests have passed.
@AlexanderBartash introduced some changes that now include all dependency plugins correctly in the tests runtime classpath.
I have also adjusted how that classpath is prepared. Before, only the bundled modules were included, which prevented bundled plugins from being present, causing #1791.
Now, all bundled plugins are also present in the runtime classpath but not in the compilation classpath, so you won't include their classes by accident.

**Closed by hsz** 2024-12-04 08:57 UTC
Labels: bug
