### ISSUE TITLE
Support for testing missing optional Idea plugins

### ISSUE THREAD

**Issue by AmailP** [JetBrains/intellij-platform-gradle-plugin#115] opened 2016-06-21 22:20 UTC
At the moment it is possible to declare a dependency on a plugin. This makes available the plugin library at compile time and at runtime.

To test the behaviour of features depending optionally on another plugin (`<depends optional="true" ...>` in plugin.xml) in case of plugin absence it is necessary to access the plugin at compile time but **not** at runtime.

An optional extra specifier could be useful to trigger this behaviour, e.g:
`plugins = ['org.intellij.plugins.markdown:8.5.0.20160208:no-runtime']`

**Comment by zolotov** [comment] 2016-06-21 22:23
As a workaround you can just disable the plugin in debug IDE

**Comment by AmailP** [comment] 2016-06-21 22:26
Sure, but I need to ensure with automated tests in CI that some functionalities are still working despite the plugin is missing.

**Comment by zolotov** [comment] 2017-04-20 13:16
Since 0.2.8 all plugins are excluded from test `runtime` in case of using Gradle >= 2.12

**Comment by baron1405** [comment] 2017-04-27 06:50
I am trying to upgrade from 0.2.7 to 0.2.8 and find that most of my unit tests break. One failure is due to my plugin not being loaded due to a missing dependency on the bundled copyright plugin. Would the runtime exclusion mentioned above cause this? If so, how can I unit test against bundled and optional plugins that are listed as dependencies? Help would be very appreciated since this is blocking our upgrading. Thanks

**Comment by zolotov** [comment] 2017-04-27 10:39
@baron1405 please show the test that is broken. 

> If so, how can I unit test against bundled and optional plugins that are listed as dependencies? 

It's supposed that all plugins will be loaded (or not, in case they are disabled) by PluginManager while setting up idea-specific test cases. If you do not want to used IDEA-specific testcases you have to add plugins to runtime classpath manually. All plugins are stored in `${prepareTestingSandbox.destinationDir}/plugins`

**Comment by baron1405** [comment] 2017-04-27 17:50
My unit tests derive from LightPlatformTestCase but I have confirmed that the problem exists with PlatformTestCase as well. These tests have been functioning fine through each plugin release through 0.2.7 and have not changed. An excerpt of a test that his failing is:
```
public class UISettingsConfigurerTest extends LightPlatformTestCase {

    @Override
    public void setUp() throws Exception {
        super.setUp();
        UISettingsConfigurer.getInstance().resetState();
    }

    public void testDefaultSettings() {
        final UISettingsConfigurer configurer = UISettingsConfigurer.getInstance();
        assertNotNull(configurer.getState());

        final UISettingsConfigurer.State state = configurer.getState();
        assertTrue(state.SHOW_MEMORY_INDICATOR);
        assertTrue(state.CLOSE_NON_MODIFIED_FILES_FIRST);
        assertEquals(10, state.EDITOR_TAB_LIMIT);
        assertTrue(state.SHOW_MAIN_TOOLBAR);
        assertFalse(state.HIDE_TOOL_STRIPES);
        assertFalse(state.SCROLL_TAB_LAYOUT_IN_EDITOR);

        final UISettings settings = UISettings.getInstance();
        assertNotNull(settings);
        assertTrue(settings.getShowMemoryIndicator());
        assertTrue(settings.getCloseNonModifiedFilesFirst());
        assertEquals(10, settings.getEditorTabLimit());
        assertTrue(settings.getShowMainToolbar());
        assertFalse(settings.getHideToolStripes());
        assertFalse(settings.getScrollTabLayoutInEditor());
    }
}
```
This test fails saying that a bundled plugin (i.e. copyright) cannot be loaded by my plugin, which has a dependency on it. Again, this test works fine in 0.2.7 and a number of previous releases.

**Comment by zolotov** [comment] 2017-04-27 18:08
> This test fails saying that a bundled plugin (i.e. copyright) cannot be loaded by my plugin,

Please attach build output

**Comment by baron1405** [comment] 2017-04-28 01:59
Here is a representative stack trace:
```
java.lang.AssertionError: Problems found loading plugins:<p/>Plugin "CThingIDEA" was not loaded: required plugin "com.intellij.copyright" not installed.<p/><br><a href="disable">Disable CThingIDEA</a><p/><a href="edit">Open plugin manager</a>
	at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:63)
	at com.intellij.testFramework.TestLogger.error(TestLogger.java:39)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.ide.plugins.PluginManagerCore.b(PluginManagerCore.java:565)
	at com.intellij.ide.plugins.PluginManagerCore.b(PluginManagerCore.java:1206)
	at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:1366)
	at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:120)
	at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:114)
	at com.intellij.idea.IdeaApplication.getStarter(IdeaApplication.java:188)
	at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.<init>(ApplicationImpl.java:218)
	at com.intellij.openapi.application.ex.ApplicationManagerEx.createApplication(ApplicationManagerEx.java:45)
	at com.intellij.idea.CommandLineApplication.<init>(CommandLineApplication.java:45)
	at com.intellij.idea.CommandLineApplication.<init>(CommandLineApplication.java:38)
	at com.intellij.idea.IdeaTestApplication.<init>(IdeaTestApplication.java:32)
	at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:52)
	at com.intellij.idea.IdeaTestApplication.getInstance(IdeaTestApplication.java:46)
	at com.intellij.testFramework.LightPlatformTestCase.initApplication(LightPlatformTestCase.java:168)
	at com.intellij.testFramework.LightPlatformTestCase.r(LightPlatformTestCase.java:270)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:58)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.LightPlatformTestCase.setUp(LightPlatformTestCase.java:268)
	at com.cthing.intellij.plugins.idea.settings.UISettingsConfigurerTest.setUp(UISettingsConfigurerTest.java:18)
	at com.intellij.testFramework.LightPlatformTestCase.B(LightPlatformTestCase.java:526)
	at com.intellij.testFramework.LightPlatformTestCase.E(LightPlatformTestCase.java:498)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$b0f40f3d.run(EdtTestUtil.kt)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Throwable
	... 44 more
```
Note that my plugin.xml has a depends on copyright.

**Comment by zolotov** [comment] 2017-04-28 09:57
> Note that my plugin.xml has a depends on copyright.

Oh, I see. I'll fix this and will add bundled plugins to runtime classpath, thanks for report.

Btw, I'd suggest do not make such dependencies in plugin.xml. It's quite strange that your plugin won't work just because user disabled `copyright` plugin, isn't it?

**Comment by zolotov** [comment] 2017-04-28 11:29
@baron1405 published 0.2.9 with the fix

**Comment by baron1405** [comment] 2017-04-28 14:08
Thanks @zolotov for the fix. That fixes the bundled plugin dependencies. However, there is still an issue with unbundled, optional plugin dependencies, in this case my use of CheckStyle-IDEA. I am not sure if the problem is because the plugin is unbundled or because I am treating it as optional. In any case they not appear to be added to the classpath. As you see above, I have a dependency on CheckStyle-IDEA, an unbundled plugin. That dependency is also optional. My unit tests are failing with:
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.infernus.idea.checkstyle.CheckStylePlugin
	at com.intellij.openapi.ui.TestDialog$1.show(TestDialog.java:23)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:276)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:301)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:312)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:737)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.newProject(ProjectManagerImpl.java:182)
	at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:263)
	at com.intellij.testFramework.PlatformTestCase.createProject(PlatformTestCase.java:254)
	at com.intellij.testFramework.LightPlatformTestCase.a(LightPlatformTestCase.java:236)
	at com.intellij.testFramework.LightPlatformTestCase.doSetup(LightPlatformTestCase.java:300)
	at com.intellij.testFramework.LightPlatformTestCase.r(LightPlatformTestCase.java:275)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:40)
	at com.intellij.testFramework.EdtTestUtil$Companion.runInEdtAndWait(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.kt)
	at com.intellij.testFramework.LightPlatformTestCase.setUp(LightPlatformTestCase.java:268)
	at com.cthing.intellij.plugins.idea.settings.folding.CodeFoldingSettingsConfigurerTest.setUp(CodeFoldingSettingsConfigurerTest.java:18)
	at com.intellij.testFramework.LightPlatformTestCase.B(LightPlatformTestCase.java:526)
	at com.intellij.testFramework.LightPlatformTestCase.E(LightPlatformTestCase.java:498)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$1.run(EdtTestUtil.kt:46)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
The corresponding plugin.xml entry is:
```
    <depends optional="true" config-file="cthing-idea-checkstyle-support.xml">CheckStyle-IDEA</depends>
```
and the referenced config-file is:
```
<idea-plugin version="2">
    <project-components>
        <component>
            <implementation-class>com.cthing.intellij.plugins.idea.settings.CheckStyleConfigurer</implementation-class>
        </component>
    </project-components>
</idea-plugin>
```
Again, this is not a new test and worked fine with 0.2.7.

To answer your question why I have a dependency on a bundled plugin, it is because my plugin actually performs configuration of IntelliJ and one of the configurations is to add a company-specific copyright.

Thanks again for the help and quick attention to this issue!

**Comment by zolotov** [comment] 2017-04-29 13:20
@baron1405 unfortunately, I won't be able to look at it for next couple weeks. However, you can try to debug the failure, it's supposed that all dependency-plugins will be load in during tests setup in `com.intellij.ide.plugins.PluginManagerCore#loadDescriptors(com.intellij.ide.StartupProgress, java.util.List<java.lang.String>)` method

**Comment by baron1405** [comment] 2017-05-18 07:53
Got some time to investigate this and got things to work by extending the "testCompile" configuration from the "ideaPlugins" configuration in my build.gradle file. The following patch would fix this in the plugin:
```diff --git a/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy b/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy
index 861cc3b..eea7009 100644
--- a/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy
+++ b/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy
@@ -71,7 +71,7 @@ class IntelliJPlugin implements Plugin<Project> {
 
         if (javaPlugin.hasProperty('COMPILE_ONLY_CONFIGURATION_NAME')) {
             project.configurations.getByName(JavaPlugin.COMPILE_ONLY_CONFIGURATION_NAME).extendsFrom idea, ideaPlugins
-            project.configurations.getByName(JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME).extendsFrom idea
+            project.configurations.getByName(JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME).extendsFrom idea, ideaPlugins
             project.configurations.getByName(JavaPlugin.TEST_COMPILE_ONLY_CONFIGURATION_NAME).extendsFrom ideaPlugins
         } else {
             project.configurations.getByName(JavaPlugin.COMPILE_CONFIGURATION_NAME).extendsFrom idea, ideaPlugins
```

**Comment by zolotov** [comment] 2017-05-18 15:09
@baron1405 this is exactly the change that I want to avoid, all plugins should be loaded from plugin's sandbox, not from classpath.

**Comment by baron1405** [comment] 2017-05-18 17:03
OK, then I am back to being confused as to how this non-builtin plugin is not available during the tests. At least I have a workaround :-)

**Comment by baron1405** [comment] 2017-05-22 18:24
The latest change to the plugin addresses my issues. Thanks @zolotov!

**Comment by Zane-XY** [comment] 2023-09-06 01:45
Came across this thread, and I want to added my situations here:
How can I ensure that a dependent optional plugin isn't automatically installed when I launch the `runIde` task to test my plugin in the Sandbox? I've declared the dependent plugin as a dependency for my plugin, but it's marked as optional. I want to verify that my plugin functions correctly even if the user doesn't have the dependent plugin installed. However, by default, IntelliJ installs the dependent plugin into the Sandbox IDE instance. How can I prevent this from happening?

**Comment by hsz** [comment] 2024-07-03 20:59
Since IntelliJ Platform Gradle Plugin `2.0.0`, it's possible to define custom test tasks and disable bundled plugins:

```
val customRunIde by intellijPlatformTesting.runIde.registering {
    type = IntelliJPlatformType.Rider
    version = "2024.2"

    plugins {
        plugin("pluginId:version")
        plugin(pluginId, version, channel)
        disablePlugins(bundledPlugiId)
    }
}

val customTest by intellijPlatformTesting.testIde.registering {
    ...
}
```

**Closed by hsz** 2024-07-03 20:59 UTC
